spring:
  cloud:
    gateway:
      routes:
        - id: host_route
          uri: http://localhost:8000  #反向代理的地址
          predicates:
            - Path=/api/user-service/haha
          filters:
            - StripPrefix=2
        - id: v2
          uri: http://localhost:8001  #反向代理的地址
          predicates:
              - Query=c,ba.*
          filters:
              - StripPrefix=2
        - id: v3
          uri: http://localhost:8000  #反向代理的地址
          predicates:
            - Query=foo,ba.*,qwer
          filters:
              - StripPrefix=2

      httpclient:
        connect-timeout: 1000
        response-timeout: 5s