spring:
  data:
    mongodb:
      uri: mongodb://192.168.21.134:27017/test
      repositories:
        type: auto
    elasticsearch:
      clusterNodes: 127.0.0.1:9300
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: trace