server:
  port: 0
spring:
  application:
    name: cms-service
  cache:
    type: redis
    redis:
      time-to-live: 300000 #expire 300s
  redis:
    url: 192.168.21.134:6379
    redisson:
      config: classpath:redisson.yml
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: always
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

mybatis:
  type-aliases-package: com.fd.swagger.dao.model.entity
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    root: info
    org.springframework: info




