server:
  port: 0
spring:
  application:
    name: cms-service
  redis:
    host: 192.168.21.134

mybatis:
  type-aliases-package: com.fd.swagger.dao.model.entity
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


